/**
 * Better Auth schema (PostgreSQL via Drizzle).
 *
 * Tables follow Better Auth's expected shape — generated by referencing
 * the official docs (https://better-auth.com/docs/concepts/database).
 * Plugin extensions:
 *   - admin plugin   → user.role / user.banned / user.banReason / user.banExpires
 *                       + session.impersonatedBy
 *   - organization   → organization, member, invitation tables
 *                       + session.activeOrganizationId
 *
 * If you add or remove plugins, regenerate via `npx @better-auth/cli generate`
 * or update this file by hand and run `npx drizzle-kit push`.
 *
 * v2 additions (2026-04-27):
 *   - organization.maxMembers / maxAdmins — quota enforcement
 *   - audit_log — immutable event log for admin actions
 */
import {
  pgTable,
  text,
  timestamp,
  boolean,
  integer,
  jsonb,
} from "drizzle-orm/pg-core";

// ----- Core: user / session / account / verification ------------------------

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),

  // admin plugin extensions
  role: text("role"),
  banned: boolean("banned"),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires"),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),

  // admin plugin
  impersonatedBy: text("impersonated_by"),
  // organization plugin — currently active org for this session
  activeOrganizationId: text("active_organization_id"),
  // impersonation extension — slug of the org being impersonated (Phase 1)
  impersonatedOrgSlug: text("impersonated_org_slug"),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// ----- Organization plugin --------------------------------------------------

export const organization = pgTable("organization", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").unique(),
  logo: text("logo"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  metadata: text("metadata"),

  // v2 quota columns — null = unlimited
  maxMembers: integer("max_members"),
  maxAdmins: integer("max_admins"),
});

export const member = pgTable("member", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  role: text("role").notNull().default("member"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const invitation = pgTable("invitation", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  email: text("email").notNull(),
  role: text("role"),
  status: text("status").notNull().default("pending"),
  expiresAt: timestamp("expires_at").notNull(),
  inviterId: text("inviter_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

// ----- Audit log (v2) -------------------------------------------------------

/**
 * Immutable event log — write-once, never update or delete rows.
 *
 * actor_id   — the user who triggered the action (admin or tenant user)
 * target_org_id — the org affected (null for platform-wide actions)
 * action     — e.g. "invitation.created", "member.removed", "impersonation.started"
 * metadata   — JSONB blob with action-specific context (email, role, slug, etc.)
 */
export const auditLog = pgTable("audit_log", {
  id: text("id").primaryKey(),
  actorId: text("actor_id"),
  actorEmail: text("actor_email"),
  targetOrgId: text("target_org_id"),
  targetOrgSlug: text("target_org_slug"),
  action: text("action").notNull(),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Re-export the full schema as `schema` so the Better Auth Drizzle
// adapter receives the table map in one shot.
export const schema = {
  user,
  session,
  account,
  verification,
  organization,
  member,
  invitation,
  auditLog,
};
